#! /bin/bash
chmod 644 /usr/lib/udev/rules.d/99-makerbase-automount.rules
chmod 644 /usr/lib/systemd/system/makerbase-automount@.service
chmod 644 /etc/makerbase-automount.d/*
chmod 777 /usr/bin/makerbase-automount
chmod 777 /usr/bin/umount_dmenu
systemctl stop moonraker.service
if [ -f /home/mks/printer_data/database/data.mdb ]; then rm /home/mks/printer_data/database/data.mdb; fi
systemctl start moonraker.service


USERNAME=sovol
if id -u ${USERNAME} >/dev/null 2>&1 ; then
    echo "User ${USERNAME} exists."
else
    useradd -d /home/sovol -g netdev -m sovol
fi

chmod 777 /root/auto_refresh
chmod 777 /root/beep.sh
chmod 777 /root/set-timezone.sh
chmod 777 /home/mks/target_timezone.txt

chgrp netdev /home/mks/ -R
chown mks /home/mks/ -R

systemctl enable makerbase-beep.service
systemctl enable makerbase-timezone-monitor.service
